[package]
name = "okane-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
chrono = "0.4.24"
log = "0.4"
nom = "7.1"
rust_decimal = "1.28"
strum = { version = "0.24", features = ["derive"] }
thiserror = "1.0"
unicode-width = "0.1.10"

[dev-dependencies]
indoc = "1.0"
maplit = "1.0"
pretty_assertions = "1.3"
rust_decimal_macros = "1.27"
