name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    name: Build for ${{ matrix.target }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x86_64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          # Find time to fix cross-build
          # - build: linux-aarch64-musl
          #   os: ubuntu-latest
          #   target: aarch64-unknown-linux-musl
          - build: windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - build: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
          - build: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # v1.94.1
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      # Cross-compilation helper for Linux
      - name: Install packages (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends xz-utils liblz4-tool musl-tools
      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }} --verbose
      - name: Package Artifacts
        shell: bash
        run: |
          staging="okane-${{ github.ref_name }}-${{ matrix.target }}"
          outdir="target/${{ matrix.target }}/release"
          mkdir "$staging"
          cp README.md README.ja.md LICENSE CHANGELOG.md "$staging/"
          if [[ "${{ matrix.os }}" =~ windows.* ]]; then
            cp "$outdir/okane.exe" "$staging/"
            cd "$staging"
            7z a "../$staging.zip" .
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp "$outdir/okane" "$staging/"
            tar czf "$staging.tar.gz" -C "$staging" .
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi
      - name: Upload to Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: |
            ${{ env.ASSET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
